### ISSUE TITLE
use of deprecated 'showSnackBar' method

### ISSUE THREAD

**Issue by x0apr** [adeleyeayodeji/ade_flutterwave_working_version#1]
package fails to run in flutter 3 due to use of deprecated 'showSnackBar' method

error message:
The method 'showSnackBar' isn't defined for the class 'ScaffoldState'

**Comment by adeleyeayodeji** [comment]
The package is developed in flutter 3, how did you implement it?

**Comment by x0apr** [comment]
As per your guidelines
 
I am using flutter 3.3.4,
changing **_scaffoldKey.currentState?** to **ScaffoldMessenger.of(context)** solves the problem

**Comment by adeleyeayodeji** [comment]
Awesome 😎
